/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yRNlczVViMq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

export function Home() {
  return (
    <div className='flex min-h-screen w-full flex-col items-center justify-center bg-[#0D1117] px-4 md:px-6 '>
      <div className='space-y-6 text-center '>
        <h1 className='text-3xl font-bold tracking-tighter text-white sm:text-4xl md:text-5xl lg:text-6xl '>
          DeSat
        </h1>
        <p className='text-white'>
          Own & Control the Future of Space Exploration
        </p>
        <form className='flex w-full max-w-3xl items-center rounded-md bg-[#21262D] px-4 py-2 text-white shadow-lg'>
          <SearchIcon className='w-5 h-5 text-white' />
          <input
            type='search'
            placeholder='Search for satellites, missions, and more...'
            className='w-full px-2 py-1 text-white bg-transparent focus:outline-none focus:ring-0'
          />
        </form>
      </div>
    </div>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <circle cx='11' cy='11' r='8' />
      <path d='m21 21-4.3-4.3' />
    </svg>
  );
}
